# Example markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

# MD013/line-length : Line length :
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
MD013:
  line_length: 90
  heading_line_length: 90
  code_block_line_length: 90

# MD024/no-duplicate-heading : Multiple headings with the same content :
# https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md024.md
MD024:
  # Only check sibling headings
  siblings_only: true
