extends: default

rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max: 1
  empty-values: enable
  line-length:
    max: 90
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: false
    check-keys: true
  truthy:
    check-keys: false
